### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by vladwix** [DonDokidon/Newspaper#10]
1. На данный момент чтение конфига происходит два раза раздельно. Это не есть гуд по причине перформанса, а самое главное, нельзя указать путь до конфига, он захардкожен как `conf.json`. Т.е. нужно сначала сменить рабочую директорию на ту, где лежит conf.json и только потом запускать программу. Если я хочу иметь несколько разных конфигов в одной папке это тоже не прокатит с таким подходом. Параметризировать конфиг можно из cli аргумента (или переменной окружения), если его нет то использовать дефолтное `conf.json`

2. В `Newspaper.DB.API.*` очень много функций-оберток такого вида:
```haskell
getNewsById :: ConnectInfo -> NewsId -> IO News
getNewsById connInfo newsId = do
  conn <- connect connInfo
  ret <- getNewsById' conn newsId
  close conn
  return ret
```
У всех (или по крайней мере у большинства) у них одинаковый функционал, надо подумать как можно абстрагироваться и заменить одной функцией для всего.

3. SQL код, завернутый в строки, склееный с помощью `<>`, да еще и с кучей `\"` очень неудобно читать, как насчет использовать `Database.PostgreSQL.Simple.SqlQQ`?

4. В модулях `Newspaper.Handlers.*.*` есть много дублирующих друг друга функций, например `wrongInput`, `notFound`, `unknownError`, их лучше вынести в отдельный модуль.

**Comment by DonDokidon** [comment]
1. Сделано. Они же читаются единожды при старте, зачем все настолько оптимизировать?
2. Они уже давно не используются, удалил их.
3. Я бы с радостью сделал так изначально, но оно отказывается работать с моим VSC.
4. Дефолтные для всех вынес

**Comment by vladwix** [comment]
1. Да, это не критично, но почему бы и нет)
3. Стоило бы заморочиться, _quasiquoting_ одна из очень удобных фич хаскеля, зачем же жертвовать ею из-за такой мелочи как подсветка синтаксиса? SQL кода в этом проекте много, у него ключевая функция, а синтаксический шум сильно ухудшает его восприятие

**Comment by DonDokidon** [comment]
Ну мне кажется, что удобство разработки => скорость немного важнее, чем лишние кавычки и эскейп-символы в запросах. Энивей, я таки смог это починить и все исправил.
