### ISSUE TITLE
Построение ответов

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Newspaper#14]
Думаю стоит вынести построение ответов в отдельные функции.
Например, чтобы выглядело так:
```
responseWithText status200 "Category created."
responseWithJSON status200 (encode entity)
```
Или даже так:
```
response200WithText "Category created."
response200WithJSON (encode entity)
```

**Comment by DonDokidon** [comment]
Сделал только для успешных респонсов, т.к считаю, что подобные изменения для ошибок ни чуть не сделают код читабельнее или удобнее (если вообще хуже не сделают). Скажи, если считаешь иначе - исправлю

**Comment by olegromashin** [comment]
Мне кажется для отрицательных ответов можно сделать функции со статусом в аргументе, например:
`responseWithText status405 "Error."`
вместо
`responseLBS status405 [("Content-Type", "text/plain")] "Error."`
Неужели думаешь, что второй вариант лучше? Кстати лучше испольовать `respond`, а не `response`, наверное. Только потом про это подумал)

Две причины для создания этого ишью:
1. Вынесенный повторяющийся код легче поддерживать.
2. В идеале логика не должна содержать деталей реализации. Это один из аспектов управления сложностью. Здесь важность этого не так заметна, т. к. у тебя всего лишь список из одного кортежа прячется, но представь, если у тебя 10-20 функций будут какие-то свои тонкости в виде аргументов требовать. Придётся вести за собой кучу импортов, придётся держать всё это в голове, другим придётся изучать всё это при работе с кодом.

**Comment by olegromashin** [comment]
Кстати. Старайся коммиты по смыслу разделять, даже если в каком-то коммите очень небольшие изменения, и сообщение коммита делать более описательным.
Например:
added ByteString unpack into readOrThrow
renamed variables that contain returned values of execute function

**Comment by DonDokidon** [comment]
Произошло недопонимание. Изначально я подумал, что ты предлагаешь мне изменить respOn... функции, чтобы они принимали не Response, а текст и коды (как я с respOnSuccess и сделал), но в respOnError это вписывалось плохо из-за существования дефолтных респонсов. В итоге я решил сделать билдер и только тогда понял, что ты этого и хотел :)  
Сделал.
