### ISSUE TITLE
Именование переменых

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Newspaper#15]
`i <- execute...`
Так лучше не делать. Чтобы разобраться с этим надо лезть в документацию. Да, это не такая большая проблема, но опять же, в идеале код должен читаться максимально просто. К тому же в проектах по-сложнее может использоваться куча различных библиотек и лезть в тонкости работы каждой функции будет проблематично.
Лучше сделать что-то вроде такого:
`affectedRows <- execute...`

**Comment by DonDokidon** [comment]
Сделано
