### ISSUE TITLE
Именование переменной, хранящей возвращаемое значение execute

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Newspaper#17]
Можешь объяснить, почему `m` добавил в `mAffectedRowsCount`?

**Comment by DonDokidon** [comment]
В Java часто (по крайней мере во всех исходниках что я читал) перед переменной добавляется m. Насколько я понимаю это делается, чтобы перевести из Pascal в Camel-case. Дополнительно это отделяет имена переменных от функций, имена которых "чистые" (без m).
В общем моего словарного запаса часто не хватало, чтобы придумать другое "чистое" имя для данных из полей и других результатов функций, поэтому я решил перенять подход с m и все переменные писать так, а все функции оставить  как есть

**Comment by olegromashin** [comment]
Хмм. Ну субъективно мне кажется странным всё это)
Во-первых этот стиль соблюдён не во всём проекте, поэтому читающему будет казаться, что `m` всё-таки имеет какой-то смысл в данном случае.
Помимо этого, мне кажется, что это какая-то устаревшая практика среди программистов, которые дают функциям имена состоящие из существительных, что не есть хорошо.
По-поводу дублирования имён рекордов и имён для возвращаемых значений из функций: ну тут да, иногда приходится крутиться. Расширение RecordWildCards очень хорошо помогает.

**Comment by DonDokidon** [comment]
Я решил использовать такой подход к именованию всего пару коммитов назад, поэтому менял только код, который попадался на глаза. Сейчас переименовал весь основной код. 
На мой взгляд получилось довольно удобно. 
1. Если нужна переменная, то пишешь m и выбираешь из списка нужную, если нужна функция, то не пишешь и они не мешаются в списке (ну кроме тех случаев, когда функция на m :) ). 
2. Теперь по большей части видно где функция, а где переменная сразу
3. Можно не париться с именованием и ты 100% не перекроешь какую-нибудь функцию случайно и не будешь потом это исправлять
