### ISSUE TITLE
Стиль именования

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Newspaper#2]
Стоит придерживаться одного стиля именования и функций, и полей в типах (snake_case и camelCase) .
https://github.com/DonDokidon/Newspaper/blob/4890e5a2b2916ea3363beadf7dfc77f0a299040f/src/Newspaper/Handlers/NewsHandler.hs#L61-L74

**Comment by catdarick** [comment]
Также для удобства работы с JSON можно воспользоваться вот [этим](https://hackage.haskell.org/package/aeson-casing-0.2.0.0/docs/Data-Aeson-Casing.html)

**Comment by DonDokidon** [comment]
Сделано
