### ISSUE TITLE
Стоит разбить файлы

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Newspaper#3]
В текущем виде файлы получились большими. Стоит создать папку для каждого handler'а и поместить реализации для get, delete и др. методов в отдельные файлы
https://github.com/DonDokidon/Newspaper/blob/4890e5a2b2916ea3363beadf7dfc77f0a299040f/src/Newspaper/Handlers/NewsHandler.hs#L3

**Comment by DonDokidon** [comment]
Сделано
