### ISSUE TITLE
Пересмотреть подход к сбору параметров

### ISSUE THREAD

**Issue by catdarick** [DonDokidon/Newspaper#4]
Текущий подход хоть и оптимален по скорости, но порождает очень много бойлерплейта. На мой взгляд, стоит реализовать какую-то функцию, которая будет искать необходимый параметр в списке по имени, избавившись от паттерн матичинга. 
https://github.com/DonDokidon/Newspaper/blob/4890e5a2b2916ea3363beadf7dfc77f0a299040f/src/Newspaper/Handlers/NewsHandler.hs#L108

**Comment by DonDokidon** [comment]
Переделал, вроде сносно
