### ISSUE TITLE
Некоторые имена переменных не соответствуют хранящимся в них данным

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Newspaper#5]
Например здесь: https://github.com/DonDokidon/Newspaper/blob/main/src/Newspaper/Handlers/UserHandler/Delete.hs#L41
Ты получаешь идентификатор, а переменной даёшь имя user, как сущность User. Так ты вводишь в заблуждение, лучше переименовать в userId, чтобы имя отражало то, что там хранится. Надо по всему проекту пробежаться на предмет таких недочётов.

**Comment by DonDokidon** [comment]
Вроде все исправил
