### ISSUE TITLE
Постараться не пользоваться исключениями

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Newspaper#7]
Я думаю проект уже можно не рефакторить, но в будущем там где ты можешь обойтись без исключений, лучше обойтись без исключений.
Язык и библиотека предоставляют средства, которые намного удобнее и безопаснее. Например Either и ExceptT.
Лучшая практика - это ловить только чужие исключения и не вводить свои.

**Comment by DonDokidon** [comment]
Честно говоря я не разобрался как ExceptT нормально пользоваться. На выходе получаются исключение неизвестного типа, т.е я не могу использовать case или паттерн матчинг, чтобы обрабатывать каждое исключение по-своему. Функции для обработки нескольких исключений, как в Control.Monad.Catch я не нашел. Как вариант можно ловить выбрасываемые исключения при помощи Control.Monad.Catch$catches, превращать их в какую-то обертку для всех возможных ошибок и потом уже паттерн матчингом все это обрабатывать, но это явно не выглядит "удобнее и безопаснее".

**Comment by olegromashin** [comment]
ExceptT это трансформер с эффектом Either. Он возвращает ошибку, а не исключение. Чем ты его параметризуешь, такая ошибка тебе и вернётся.

**Comment by DonDokidon** [comment]
Это понятно, просто чтобы вывести ошибку, приходится ее внутри ловить и переводить в Left и дополнительно оборачивать  во что-то, чтобы на выходе это обработать, в итоге то что я сейчас в одном месте ловлю и обрабатываю превратилось бы в кучу дополнительного кода. Да, в результате можно чуть проще понять, что функция может вернуть ошибку, но оно того не стоит имхо, все равно придется лезть в документацию/реализацию, чтобы понять, какие ошибки могут быть.
Но это касается лишь моей попытки переписать текущий код под ExceptT, возможно если бы я изначально проектировал код под него, то получилось бы хорошо. В общем замечание взял на заметку, постараюсь придерживаться
