### ISSUE TITLE
Стараться использовать сильную типизацию языка по максимуму

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Newspaper#8]
Сильная типизация нужна, чтобы обезопасить программистов от ошибок. Сейчас у тебя все идентификаторы типа Int. Это создаёт уязвимое место. В логике при работе с несколькими сущностями ты можешь случайно передать не тот идентификатор и испортить данные в бд.
Здесь есть 2 способа:
1. Создать для каждой сущности свою тип-обёртку для Int идентификатора.
2. Использовать тип с фантомным параметром. Почитать можно здесь: https://kowainik.github.io/posts/haskell-mini-patterns#phantom-type-parameters

**Comment by DonDokidon** [comment]
Вроде исправлено. Использовал обертки, т.к в коде это выглядит понятнее имхо.
