### ISSUE TITLE
Не вводить глобальные аббревиатуры

### ISSUE THREAD

**Issue by olegromashin** [DonDokidon/Newspaper#9]
Есть такие имена как:
throwNAK
throwLOND
throwAD

Я понимаю, что это создаёт более короткое имя, с которым удобнее работать. Но по возможности лучше снижать когнитивную нагрузку. Чем больше аббревиатур, тем сложнее в итоге будет понимать код При необходимости аббревиатуры лучше вводить локально только внутри функций.

К тому же можно не писать все слова, а сделать, например, так:
throwLackOfData

**Comment by DonDokidon** [comment]
Исправлено
